name: StarlexHub
version: '1.0-SNAPSHOT'
main: net.starlexpvp.starlexHub.StarlexHub
api-version: '1.21'
dependencies:
  server:
    LuckPerms:
      load: AFTER
      required: true
      join-classpath: true